version: '3.9'
services:
  tour-de-france-mvc:
    image: emilesherrott/tour-de-france-mvc-cloud:0.0.1.RELEASE
    ports:
      - "3000:3000"
    depends_on:
      - tour-de-france-db
    restart: always
    networks:
      - tour-network

  tour-de-france-db:
    image: emilesherrott/tour-de-france-db-cloud:0.0.1.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - tour-network
      
networks:
  tour-network: